# escape=`
ARG JAVA17_IMAGE_VERSION=3206.vb_15dcf73f6a_9-10
ARG PYTHON_VERSION=3.12.3

FROM python:"${PYTHON_VERSION}"-windowsservercore-1809 AS python-core

# ProgressPreference => Disable Progress bar for faster downloads
SHELL ["powershell.exe", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# hadolint ignore=DL3013
RUN "C:/Python/python.exe" -m pip install --no-cache-dir --upgrade pip; `
  pip install --no-cache-dir setuptools wheel;

# Adding jdk8 from Adoptium MSI installer (cannot only run msiexec.exe on ServerCore, NOT on nanoserver)
# WARNING: JDK8 has a different URL pattern than the others (/jdk8<...>/ instead of /jdk-17<...>/)
ARG JAVA_VERSION=jdk8u412-b08
RUN New-Item -ItemType Directory -Path C:\temp | Out-Null ; `
    $msiUrl = 'https://api.adoptium.net/v3/installer/version/{0}/windows/x64/jdk/hotspot/normal/eclipse?project=jdk' -f $env:JAVA_VERSION.Replace('+', '%2B') ; `
    Invoke-WebRequest $msiUrl -OutFile 'C:\temp\jdk.msi' ; `
    $proc = Start-Process -FilePath 'msiexec.exe' -ArgumentList '/i', 'C:\temp\jdk.msi', '/L*V', 'C:\temp\OpenJDK.log', '/quiet', 'ADDLOCAL=FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome',  'INSTALLDIR=C:\javaruntime' -Wait -Passthru ; `
    $proc.WaitForExit() ; `
    Remove-Item -Path C:\temp -Recurse | Out-Null

# Use inbound-agent's jdk17 only for running jenkins agent, not as default java
FROM jenkins/inbound-agent:${JAVA17_IMAGE_VERSION}-jdk17-nanoserver-1809

# ProgressPreference => Disable Progress bar for faster downloads
SHELL ["pwsh.exe", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Adding python
COPY --from=python-core C:/Python C:/tools/python

# Install Launchable in this layer
ARG LAUNCHABLE_VERSION=1.66.0
RUN "C:/tools/python/python.exe" -m pip install --no-cache-dir launchable=="${env:LAUNCHABLE_VERSION}";

# Adding jdk8 from eclipse-temurin
ENV JAVA_HOME="C:\tools\jdk-8"
COPY --from=python-core C:/javaruntime $JAVA_HOME

# https://github.com/StefanScherer/dockerfiles-windows/tree/master/golang-issue-21867
COPY --from=python-core C:/windows/system32/netapi32.dll C:/windows/system32/netapi32.dll
COPY --from=python-core C:/windows/system32/whoami.exe C:/windows/system32/whoami.exe

ARG MAVEN_VERSION=3.9.6
RUN Invoke-WebRequest -Uri "https://archive.apache.org/dist/maven/maven-3/${env:MAVEN_VERSION}/binaries/apache-maven-${env:MAVEN_VERSION}-bin.zip" -OutFile ${env:TEMP}/apache-maven.zip ; `
  Expand-Archive -Path "${env:TEMP}/apache-maven.zip -Destination" C:/tools ; `
  Remove-Item ${env:TEMP}/apache-maven.zip ;

ENV PYTHON_PATH="C:\tools\python;C:\tools\python\Scripts"
ENV MAVEN_HOME="C:\tools\apache-maven-${MAVEN_VERSION}"
ENV PATH="${PYTHON_PATH};${JAVA_HOME}\bin;${PATH};${MAVEN_HOME}\bin;"
